spring:
  datasource:
    username: ${DB_USER_NAME}:sa
    password: ${DB_PASSWORD}:password
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8678
  servlet:
    context-path: /user-service